filegroup(
    name = "java_srcs",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)

java_library(
    name = "app",
    srcs = [":java_srcs"],
    visibility = ["//visibility:public"],
)
